# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'h:\DataSet\ht_dataset\FileRename\tabs\tab_digit.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_TabDigit(object):
    def setupUi(self, TabDigit):
        TabDigit.setObjectName("TabDigit")
        TabDigit.resize(695, 420)
        self.verticalLayout = QtWidgets.QVBoxLayout(TabDigit)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_sortRule = QtWidgets.QLabel(TabDigit)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_sortRule.setFont(font)
        self.label_sortRule.setObjectName("label_sortRule")
        self.horizontalLayout_2.addWidget(self.label_sortRule)
        self.radioButton_sortByName = QtWidgets.QRadioButton(TabDigit)
        self.radioButton_sortByName.setChecked(True)
        self.radioButton_sortByName.setObjectName("radioButton_sortByName")
        self.horizontalLayout_2.addWidget(self.radioButton_sortByName)
        self.radioButton_sortByReversedName = QtWidgets.QRadioButton(TabDigit)
        self.radioButton_sortByReversedName.setObjectName("radioButton_sortByReversedName")
        self.horizontalLayout_2.addWidget(self.radioButton_sortByReversedName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_mould = QtWidgets.QLabel(TabDigit)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_mould.setFont(font)
        self.label_mould.setObjectName("label_mould")
        self.horizontalLayout_3.addWidget(self.label_mould)
        self.lineEdit_mould = QtWidgets.QLineEdit(TabDigit)
        self.lineEdit_mould.setObjectName("lineEdit_mould")
        self.horizontalLayout_3.addWidget(self.lineEdit_mould)
        self.label_example = QtWidgets.QLabel(TabDigit)
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_example.setFont(font)
        self.label_example.setObjectName("label_example")
        self.horizontalLayout_3.addWidget(self.label_example)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(TabDigit)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_numStart = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_numStart.setFont(font)
        self.label_numStart.setObjectName("label_numStart")
        self.gridLayout.addWidget(self.label_numStart, 0, 0, 1, 1)
        self.lineEdit_numStart = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_numStart.setObjectName("lineEdit_numStart")
        self.gridLayout.addWidget(self.lineEdit_numStart, 0, 1, 1, 1)
        self.label_numStep = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_numStep.setFont(font)
        self.label_numStep.setObjectName("label_numStep")
        self.gridLayout.addWidget(self.label_numStep, 1, 0, 1, 1)
        self.lineEdit_numStep = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_numStep.setObjectName("lineEdit_numStep")
        self.gridLayout.addWidget(self.lineEdit_numStep, 1, 1, 1, 1)
        self.checkBox_numLen = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_numLen.setObjectName("checkBox_numLen")
        self.gridLayout.addWidget(self.checkBox_numLen, 2, 0, 1, 2)
        self.label_numLen = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_numLen.setFont(font)
        self.label_numLen.setObjectName("label_numLen")
        self.gridLayout.addWidget(self.label_numLen, 3, 0, 1, 1)
        self.lineEdit_numLen = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_numLen.setObjectName("lineEdit_numLen")
        self.gridLayout.addWidget(self.lineEdit_numLen, 3, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(TabDigit)
        QtCore.QMetaObject.connectSlotsByName(TabDigit)

    def retranslateUi(self, TabDigit):
        _translate = QtCore.QCoreApplication.translate
        TabDigit.setWindowTitle(_translate("TabDigit", "Form"))
        self.label_sortRule.setText(_translate("TabDigit", "重命名排序规则："))
        self.radioButton_sortByName.setText(_translate("TabDigit", "按文件名正序"))
        self.radioButton_sortByReversedName.setText(_translate("TabDigit", "按文件名逆序"))
        self.label_mould.setText(_translate("TabDigit", "模板："))
        self.label_example.setText(_translate("TabDigit", "例：<self>_#"))
        self.groupBox.setTitle(_translate("TabDigit", "数字设置"))
        self.label_numStart.setText(_translate("TabDigit", "开始："))
        self.lineEdit_numStart.setText(_translate("TabDigit", "0"))
        self.label_numStep.setText(_translate("TabDigit", "步长："))
        self.lineEdit_numStep.setText(_translate("TabDigit", "1"))
        self.checkBox_numLen.setText(_translate("TabDigit", "不足位数补齐"))
        self.label_numLen.setText(_translate("TabDigit", "位数："))
        self.lineEdit_numLen.setText(_translate("TabDigit", "3"))

